### PR TITLE
Cu 86b16h8t2 create front end project steven smodish

### PR DESCRIPTION
**Pull request by ssmodish**

### CODE REVIEW

**Comment by allantito** [comment]
Task linked: [CU-86b16h8t2 Create Front-end project](https://app.clickup.com/t/86b16h8t2)

**Comment by ssmodish** [comment]
Closed PR due to front-end project not being integrated into monorepo

**Comment by ssmodish** [comment]
PR re-opened now the front end project has been integrated into monorepo.

**Review by AlexVCS — APPROVED** [review]
Looks good to me!

**Pull request merged**
